set shell := ['nu', '-c']
set dotenv-load

docker-build:
    docker build --build-arg userid=(id -u) --build-arg groupid=(id -g) --build-arg username (id -un) -t android-build .   
docker-run:
    docker run --privileged -it --rm -v .:/src android-build
