name: ci

on:
  push:
    branches:
      - 'master'
    paths:
      - 'build-env-flutter-rust-android/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push build-env-flutter-rust-android
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build-env-flutter-rust-android/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/build-env-flutter-rust-android:latest
