name: ci

on:
  push:
    branches:
      - 'master'
    paths:
      - 'webrtc-build/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push webrtc-build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./webrtc-build/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webrtc-build:latest
